### ISSUE TITLE
Request - fromiso/frugal to full install

### ISSUE THREAD

**Issue by anticapitalista** [gazelle-installer/gazelle-installer#113]
A request.

At the moment, if user boots fromiso or is running a frugal install on lets say sda4, it is not possible to do a normal install onto any other partition eg sda3. The cli-installer can do this, but the gui one doesn't show any options. Is it possible to change this?

**Comment by dolphinoracle** [comment]
at the moment you need to adjust the installer.conf file to not apply the
boot device filter.

I don't think there is a commandline switch but will check.

**Comment by dolphinoracle** [comment]
there is not a command line switch at the moment.  the value to change in
/usr/share/gazelle-installer-data/installer.conf is
"INSTALL_FROM_ROOT_DEVICE".

**Comment by anticapitalista** [comment]
I completely missed that one. Tested installing a frugal install to a full install after editing that file. Worked a treat.
