### ISSUE TITLE
system-keyboard-qt replaces fskbsetting

### ISSUE THREAD

**Issue by anticapitalista** [gazelle-installer/gazelle-installer#120]
line 3154 of minstall.cpp reads proc.exec("env GTK_THEME='Adwaita' fskbsetting", false);

should be

proc.exec("env GTK_THEME='Adwaita' system-keyboard-qt", false);

**Comment by dolphinoracle** [comment]
If you have system-keyboard-qt in the antix repo then the change is ok.

Mx cannot change just yet...have to add system-keyboard-qt to the main repo
first.  That and updating mx-goodies is required.  I'm mentioning this for
adrian so he doesn't rush to package and make a change.

**Comment by anticapitalista** [comment]
Ok. I thought the installer changes were only for MX/antiX-21.

**Comment by chkboom** [comment]
Latest version of the installer now uses system-keyboard-qt, falling back to fskbsetting if needed.
