### ISSUE TITLE
we need zfs rootfs plus zfs kernel for first install 

### ISSUE THREAD

**Issue by osevan** [gazelle-installer/gazelle-installer#135]
We need easy solution for zfs rootfs for storage guys.

Please make a testing one

I have installed MX in over 30 notebooks and on some desktops with space and more HDDs than 4.

Dont forget to ask zfs flags like "-ashift" and zfs native crypting disk option with algorithm selection  at first install in installer.

Zfs is the right solution for storage.
Thanks and

Best regards

**Comment by chkboom** [comment]
I'd love to know what PCs you have that contain more than four 1-exabyte HDDs.
There is currently no ZFS in the mainline Linux kernel, so the installer does not have this option.
For encryption, you can select the "Encrypt" checkbox.
