### ISSUE TITLE
Gazelle installer makes trouble with f2fs installation.

### ISSUE THREAD

**Issue by osevan** [gazelle-installer/gazelle-installer#137]
Gazelle installer makes trouble with f2fs installation.

Other filesystem's like ext4 and xfs installing fast on ssd

But with f2fs root fs installing was after 6 h 60 %
Im ysing latest antix iso downloadable by mirror.

Antix64 full no ahc

**Comment by anticapitalista** [comment]
It's a grub issue it seems. grub on antiX-19 series is version 2.02 and f2fs needs grub >=2.3

**Comment by osevan** [comment]
OK fixed  with bullseye a2 release
