### ISSUE TITLE
feature request for btrfs subvolume selection

### ISSUE THREAD

**Issue by durapensa** [gazelle-installer/gazelle-installer#143]
I recently installed MX Linux using a customized disk layout to select a btrfs root fs, adding the options `defaults,noatime,compress=zstd`. This works great and the functionality is fantastic.

To facilitate Timeshift backups, could the gazelle-installer be enhanced to interpret the btrfs option `subvol=` to create & use the indicated subvolume? E.g. to follow the practice to label the root subvolume `@` and the home subvolume `@home`, etc.

**Comment by dolphinoracle** [comment]
it sort of does now.  what you need to do is create a subvolume first.  the installer will add the subvol= line to fstab automatcially, you don't need to specify it in the options, and you can specify all the other options on the line in the installer pointed at the subvolume.   Its not real clear but in the partition setup if you can right click on a btrfs partition and select "New Subvolume".

**Comment by durapensa** [comment]
Thank you, that worked. A pull-down arrow on the device name to present the context menu might help with visibility of this feature. I tried manually creating the subvolumes first, to use the 'Scan subvolumes' menu action mentioned in the help, but didn't see 'Scan subvolumes' in the context menu. Am I missing something or does the 'Subvolumes' help section need an update?

**Comment by chkboom** [comment]
The "Scan subvolumes" menu only works if you have an existing Btrfs partition. That option should populate the list with subvolumes that are already on the file system.
