### ISSUE TITLE
Incorrect partition size

### ISSUE THREAD

**Issue by Carmina16** [gazelle-installer/gazelle-installer#146]
When installing on a disk that has free space in sectors `2048..16777215`, and "use all disk" option is selected, the installer tries to create a partition from `1MiB` to `8297MiB` and fails as it is outside of the disk.

**Comment by chkboom** [comment]
Can you please update the installer to the latest available and try again? If this still happens, send the installer log (/var/log/minstall.log).

**Comment by Carmina16** [comment]
In the latest MX Linux version the installer now creates a swap file when the "all disk" option is selected. Is that an intended change or something is wrong?

**Comment by chkboom** [comment]
The installer has always created a swap partition for the whole disk install.

**Comment by chkboom** [comment]
Since there has been no response for 3 weeks, I will assume this issue has been resolved.
