### ISSUE TITLE
Some translation issues

### ISSUE THREAD

**Issue by anticapitalista** [gazelle-installer/gazelle-installer#148]
lupdate *.cpp *.h *.ui -ts minstall_en.ts
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1791: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1791: Class 'DeviceItem' lacks Q_OBJECT macro
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1792: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1793: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1916: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1919: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1920: Cannot invoke tr() like this
/home/anticap/debs2upload/bullseye/gazelle-installer-1.7.2/partman.cpp:1921: Cannot invoke tr() like this
Updating 'minstall_en.ts'...
    Found 362 source text(s) (362 new and 0 already existing)

**Comment by chkboom** [comment]
fixed, thanks
