### ISSUE TITLE
Failed to mount partition.

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [gazelle-installer/gazelle-installer#171]
i compiled gazelle-installer 23.8.01 in debian 11 (MX 21.3)
but after complete make a snapshot for my custom distro (Devubox), there is error when installing due to 
`mount: unrecognized option '--mkdir'`
![Screenshot_debian11_2023-08-14_17:12:13](https://github.com/gazelle-installer/gazelle-installer/assets/78845241/1de9e83b-262d-4540-aaa0-2850ab15ce0b)
mx installer log:
[minstall.log](https://github.com/gazelle-installer/gazelle-installer/files/12333755/minstall.log)
when mx-installer 23.8.01 arrive in the repository for debian 11 (MX 21.3)

**Comment by TheBSODAndWSODFan** [comment]
why i want new version of mx-installer
because it easier to make swapfile in 23.8.01

**Comment by chkboom** [comment]
There is no official 23.8.01mx21 installer, so I'm not sure where you got that version from. The latest installer that supports MX Linux 21 is 23.6.02.

If you want to compile from source for MX 21, use the bullseye branch. The latest code in master only supports MX Linux 23. There are no plans to backport this code to MX 21 or earlier.

**Comment by TheBSODAndWSODFan** [comment]
i got that version by change it from 23.8.01mx23 to 23.8.01mx21 in changelog file and recompiled it using source code from mx repo
http://la.mxrepo.com/mx/repo/pool/main/g/gazelle-installer/gazelle-installer_23.8.01mx23.tar.xz

**Comment by chkboom** [comment]
The 23.8.01mx23 (v5) installer is not supported on MX 21. Why did you change the version number? It won't actually change anything in the installer, and will only complicate diagnostics.
If you want swap files on installation, you should probably just create a new snapshot based on MX 23. Otherwise, stick with the official 23.6.02 ("v4") and don't create any swap partitions, it's relatively easy to make the swap files after installation.

**Comment by TheBSODAndWSODFan** [comment]
i change the version number and recompiled, because the precompiled mx23 version. is need `libc6 >=2.34` 
i don't think, the mount mkdir error due to changes in this commit https://github.com/gazelle-installer/gazelle-installer/commit/4de6b27d8ffd75aa7eb3bdcb094fe5ff4841b608

**Comment by chkboom** [comment]
The --mkdir option is probably not available on MX 21. There are a few other things I think, that needed changing also in order to work with MX 21.

Why not base the snapshot off MX 23 instead?

**Comment by TheBSODAndWSODFan** [comment]
finally it worked after modifying the source code in base.cpp and partman.cpp, but it give another error 
![Screenshot_debian11_2023-08-17_21:56:22](https://github.com/gazelle-installer/gazelle-installer/assets/78845241/c40ac598-f7e0-4f50-9f07-cf1612bfb7a7)
[minstall2.log](https://github.com/gazelle-installer/gazelle-installer/files/12378045/minstall2.log)

this is patch file that i make. can you determine error in partman.cpp?
[patch.tar.gz](https://github.com/gazelle-installer/gazelle-installer/files/12378080/patch.tar.gz) for 23.8.01

**Comment by chkboom** [comment]
Look in the log file, it should have that same error you see. Usually immediately before that line, you should be able to work out what is going on.

But running 23.8.01 on Bullseye is an unsupported use case. This version is only ever tested on MX 23, and chances are that if you start fiddling with one bit of the source, you'll likely run into an issue where another feature isn't working, and this can cascade on. Again, if you want the latest features, use MX 23.

**Comment by TheBSODAndWSODFan** [comment]
i know is unsupported. but it is important for next update of devubox alpha2r2.
i was getting error.
`2023-08-18 07:15:59.093 DBG default: SErr #17: "/usr/sbin/mkswap: invalid option -- 'q'\nTry 'mkswap --help' for more information.\n"`
![celluloid-shot0003](https://github.com/gazelle-installer/gazelle-installer/assets/78845241/58022382-e0e4-40be-bfb3-ecfd7147b6af)
then i fix it and, OMG!!!, it works and finished install with no issues. but keep in mind, bugs may be happen.
![Screenshot_debian11_2023-08-18_18:57:38](https://github.com/gazelle-installer/gazelle-installer/assets/78845241/8c012598-794c-4f9d-9f74-875418248f74)
[minstall4.log](https://github.com/gazelle-installer/gazelle-installer/files/12379031/minstall4.log)
this contain a deb files and patch
[mx-installer 23.8.01mx21~devubox+2.tar.gz](https://github.com/gazelle-installer/gazelle-installer/files/12379057/mx-installer.23.8.01mx21.devubox%2B2.tar.gz)

**Comment by TheBSODAndWSODFan** [comment]
because devubox is a new mx respin distro that still in alpha
i choose a Bullseye Base, because my laptop for compiling apps and daily driver are still on mx 21.3.

Devubox MX-23 may will be released soon

**Comment by chkboom** [comment]
Consider using a VM with MX 23 on it for compiling. It's a lot safer that way, any disasters are kept within the VM.
If you have trouble with virtualbox, I would recommend libvirt/virt-manager or qt-virt-manager as they use the native KVM hypervisor of the kernel, and this also plays nicely with the guest operating system.
