### ISSUE TITLE
Reusing existing btrfs partition results in invalid fstab lines during reinstall

### ISSUE THREAD

**Issue by xenotrope** [gazelle-installer/gazelle-installer#198]
Tested with MX-23.2_x64.iso. I have been able to repeat an issue in minstall-launcher that involves reinstalling MX-23 on top of an existing MX-23 btrfs partition.

In minstall-launcher, one can choose "Customize the disk layout" and format a drive with btrfs. By right-clicking the device, one can choose "Create subvolume" and create two subvolumes, @ and @home, and assign them mountpoints of / and /home, respectively.

Finishing the install, the resulting /etc/fstab file looks something like this:

```
# Pluggable devices are handled by uDev, they are not in fstab
UUID=12da9b7c-3830-4a42-9e6e-fa3169146901 / btrfs subvol=@,discard=async,noatime,compress=zstd:1 1 1
UUID=12da9b7c-3830-4a42-9e6e-fa3169146901 /home btrfs subvol=@home,discard=async,noatime,compress=zstd:1 1 2
/swap/swap swap swap defaults 0 0
```

When reinstalling on top of this existing setup, I can choose in minstall-launcher to scan the existing subvolumes, overwriting @ for / and preserving @home for /home. The resulting layout changes as defined are:

```
Reuse (no reformat) sda1
 + Overwrite subvolume @ to use for /
 + Reuse subvolume @home as /home
```

Before the install finishes, I can cat /mnt/antiX/etc/fstab and (eventually) see what the fstab will look like:

```
# Pluggable devices are handled by uDev, they are not in fstab
UUID=12da9b7c-3830-4a42-9e6e-fa3169146901 /  subvol=@,discard=async,noatime,compress=zstd:1 1 1
UUID=12da9b7c-3830-4a42-9e6e-fa3169146901 /home  subvol=@home,discard=async,noatime,compress=zstd:1 1 2
```

The swap line is absent, as I have not yet answered the swap question in the installer. Note, however, that each of the btrfs mount lines are lacking "btrfs" in the file system type field. This is shown in the second fstab by two spaces between the mountpoint, either "/" or "/home", and the "subvol=" string.

I noticed this comes, unsurprisingly, from partman.cpp in PartMan::makeFstab():

```
       // Mount point, file system
        const QString &fsfmt = volume->finalFormat();
        if (fsfmt == "SWAP") out << " swap swap";
        else {
            out << ' ' << it.first;
            if (fsfmt.startsWith("FAT")) out << " vfat";
            else out << ' ' << fsfmt;
        }
```

fsfmt is not being properly set to "btrfs" here. finalFormat() itself looks like this:

```
QString PartMan::Device::finalFormat() const noexcept
{
    if (type == SUBVOLUME) return parentItem->format;
    return (type != DRIVE && (usefor.isEmpty() || format == "PRESERVE")) ? curFormat : format;
}
```

So it would appear that this logic isn't properly identifying the parentItem as being of type btrfs even though, in the included screenshot, sda1 is clearly marked as being of type btrfs after running "Scan subvolumes".

![Screenshot_2024-01-26_04-29-19](https://github.com/gazelle-installer/gazelle-installer/assets/14990430/bf80eecc-78ab-4ec6-803c-c2891c955a92)

Manually editing /mnt/antiX/etc/fstab after it has been created by minstall-launcher to include the "btrfs" fields on the affected lines and saving the file before rebooting allows the reinstalled OS to boot as expected.

**Comment by dolphinoracle** [comment]
indeed, since the parent item is not set in this case.

thanks!

**Comment by dolphinoracle** [comment]
test deb here addressing this issue plus another:

https://github.com/MX-Linux/gazelle-installer-debian-folder-mx/raw/master/mx-installer_24.01.02mx23_amd64.deb

**Comment by xenotrope** [comment]
I've downloaded the deb and installed it to a live USB session. When re-installing with minstall-launcher it creates a valid fstab file and allows the system to boot as expected. Thank for addressing this issue.

**Comment by dolphinoracle** [comment]
good  thanks for the report and the test.
