### ISSUE TITLE
Request to add f2fs support

### ISSUE THREAD

**Issue by anticapitalista** [gazelle-installer/gazelle-installer#22]
An MX user requested this. 
Seems like it should be straightforward to include

https://wiki.archlinux.org/index.php/F2FS

Gentoo suggests these kernel options: https://wiki.gentoo.org/wiki/F2FS

     CONFIG_F2FS_FS
    F2FS_FS_XATTR
    CONFIG_F2FS_FS_POSIX_ACL
    CONFIG_F2FS_FS_SECURITY

**Comment by anticapitalista** [comment]
> What I can do is add the option and force people to put /boot on a different partition.

Sounds like the best option for now.

**Comment by AdrianTM** [comment]
> > What I can do is add the option and force people to put /boot on a different partition.
> 
> Sounds like the best option for now.

I tried, GRUB install successfully but it still fails to boot.

**Comment by anticapitalista** [comment]
> > > What I can do is add the option and force people to put /boot on a different partition.
> > 
> > 
> > Sounds like the best option for now.
> 
> I tried, GRUB install successfully but it still fails to boot.

According to the Arch wiki, you need  'NAND-based flash memory equipped with Flash Translation Layer.' Did you test on that?

**Comment by AdrianTM** [comment]
> > > > What I can do is add the option and force people to put /boot on a different partition.
> > > 
> > > 
> > > Sounds like the best option for now.
> > 
> > 
> > I tried, GRUB install successfully but it still fails to boot.
> 
> According to the Arch wiki, you need 'NAND-based flash memory equipped with Flash Translation Layer.' Did you test on that? (just checking)

That's not my understanding, the file system should work on any support, it just takes advantage of those features or relies on them to for write distribution. I was able to format a virtual drive in VBox with this file system and copy and read files to/from it.

**Comment by dolphinoracle** [comment]
check the grub.cfg to make sure the UUID of the root= matches the UUID of
the f2fs partition.

**Comment by chkboom** [comment]
Bump. Would this be a difficult thing to add for MX-19 or antiX-19?

**Comment by dolphinoracle** [comment]
closing.  this has been added to the installer.
