### ISSUE TITLE
Fails to install to external usb

### ISSUE THREAD

**Issue by anticapitalista** [gazelle-installer/gazelle-installer#85]
Reports on both MX and antiX-19 that the installer fails when trying to install to target usb.

**Comment by dolphinoracle** [comment]
I think this is related to automount.  should have fix shortly.  testing some stuff now.

**Comment by dolphinoracle** [comment]
lastest changes now deal with the antiX automount-antix and spacefm desktop.

**Comment by dolphinoracle** [comment]
incidentally, this also affected mmcblk devices which are often on the usb bus internally rather than sata.  also, tested on antiX 19 b2.
